#!/bin/sh
#
# Starts robot arm controller.
#

start() {
	echo "Starting robot controller... "
	modprobe btusb
	modprobe uinput
	hciconfig hci0 up
	rpio_pwm
	/usr/bin/wii_robot.py &
}
stop() {
	echo -n "Stopping robot controller..."
	killall wii_robot.py
}
restart() {
	stop
	start
}

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart|reload)
  	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
